version: "3.6"

services:
  postgres:
    build: "./postgres"
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: "gopher_network_db"
      POSTGRES_USER: "gophers"
      POSTGRES_PASSWORD: "golang"

  gophers:
    build: "."
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: "gopher_network_db"
      POSTGRES_USER: "gophers"
      POSTGRES_PASSWORD: "golang"

#  nginx:
#    build: "./nginx"
#    ports:
#      - "8080:80"
#    depends_on:
#      - "gophers"


